name: firebase_auth_service_interface
description: An interface for a Firebase Auth service for Flutter apps and Dart servers, providing a common API for different implementations.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  types_for_auth: ^0.0.0-a1

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.24.3
